### ISSUE TITLE
Consider exporting ES5 javascript

### ISSUE THREAD

**Issue by romgrk** [vitalets/bro-fs#1]
Trying to produce a production build with `create-react-app` and this package fails. The reason is that the exported code (in `dist/bro-fs.js`) still contains ES6 features. (see https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify)

Also, `package.json` doesnt seem to point to `dist/bro-fs.js` but to `src/index.js`. (consider using the `"browser"` field)

**Comment by vitalets** [comment]
@romgrk thanks for pointing on that. Fixed in 0.2.
