### ISSUE TITLE
Cannot list all files via readdir if files exceed 100.

### ISSUE THREAD

**Issue by yesm1994** [vitalets/bro-fs#10]
I applied bro-fs in my project , it really helps me a lot.
But found out that can only get 100 files via readddir api.

I have read the source code, and google it ,
here is the workaround:

Ref: https://stackoverflow.com/questions/23823548/maximum-files-of-a-directory-that-can-be-read-by-filereaderreadentries-in-javas

Hope you guys can fix it ASAP,  really appreciate that.

**Comment by vitalets** [comment]
Released as v0.6.0
